apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gtfs-fetch-
spec:
  entrypoint: fetch-gtfs-rt
  templates:
    - name: fetch-gtfs-rt
      container:
        image: ghcr.io/lorispolenz/fetch_gtfs:main
        secretRef:
        env:
          - name: OPEN_DATA_API_KEY
            valueFrom:
              secretKeyRef:
                name: fetch-gtfs-rt-creds
                key: OPEN_DATA_API_KEY
          - name: S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: fetch-gtfs-rt-creds
                key: S3_ENDPOINT
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: fetch-gtfs-rt-creds
                key: S3_ACCESS_KEY
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: fetch-gtfs-rt-creds
                key: S3_SECRET_KEY
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: fetch-gtfs-rt-creds
                key: S3_BUCKET
